name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Extract tag version
        id: tag_version
        run: |
              export TAG_VERSION=$(node -p "require('./package.json').version")
              echo "::set-output name=tag_version::$TAG_VERSION"

      - name: Print tag version
        run: echo ${{ steps.tag_version.outputs.tag_version }}

      - name: Build action
        run: npm run build

      - name: Create tag version
        uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: v${{ steps.tag_version.outputs.tag_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
